#:kivy 2.1.0
<Days@GridLayout>:
	cols: 7
	size_hint: 1,.2
	canvas.before:
		Color:
			rgba:237/255,191/255,88/255,0
		Rectangle:
			pos: self.pos
			size: self.size
	Label:
		text:'Ma'
		color:0,0,0,1
	Label:
		text:'Ti'
		color:0,0,0,1
	Label:
		text:'Ke'
		color:0,0,0,1
	Label:
		text:'To'
		color:0,0,0,1
	Label:
		text:'Pe'
		color:0,0,0,1
	Label:
		text:'La'
		color:0,0,0,1
	Label:
		text:'Su'
		color:0,0,0,1	