#:kivy 2.1.0
<Button>:
	background_color: 0,0,0,0
	
<Skeduler>:
	orientation:'vertical'
	Image:
		source:"images/tausta-lehdet.png"
        allow_stretch:True
        keep_ratio:False
	#canvas.before:
	#	Color:
	#		rgba: 237/255,216/255,174/255,0
	#	Rectangle:
	#		pos: self.pos
	#		size: self.size
		
	BoxLayout:
		Months:
		BoxLayout:
			orientation: 'vertical'
			Days:
			Dates:
			BoxLayout:
				size_hint:1,.15
				Status: