#:kivy 2.2.0
#:import Factory kivy.factory.Factory

<CustomSpinnerOptions@SpinnerOption>:
    # Buttonin tausta on oletuksena harmaa ja vuotaa läpi, ellei explisiitisesti laiteta "tyhjäksi"
    background_normal: ""
    background_color: 189/255, 132/255, 47/255, 1
    color: 0,0,0,1
    font_size: "14sp"

<Button>:
	background_color: (232/255, 123/255, 0/255, 0.10)

<Spinner>:
	skeduler: Factory.Skeduler
	option_cls: Factory.CustomSpinnerOptions
    background_normal: ""
	background_color: 232/255,123/255,0/255,0.10
    color: 0,0,0,1
    font_size: "14sp"

<YearSpinner@Spinner>:
	values: [str(_) for _ in range(self.skeduler.year - 5, self.skeduler.year + 5)]
	text: str(self.skeduler.year)
<MonthSpinner@Spinner>:
	values: [_ for _ in ["tammi", "helmi", "maalis", "huhti", "touko","kesä","heinä","elo","syys","loka","marras","joulu"]]
	text: str(self.values[self.skeduler.month -1])
	
<Skeduler>:
	orientation:'vertical'
	Image:
		source:"images/tausta-lehdet.png"
        fit_mode:"fill"
		
	BoxLayout:
		Months:
		BoxLayout:
			orientation: 'vertical'
			GridLayout:
				size_hint: 1, .15
				rows: 1
				cols: 4
				MDIconButton:
					icon: "arrow-left"
					text_color: 0,0,0,1
					on_press: root.set_month(root.month-1)
				YearSpinner:
				MonthSpinner:
				MDIconButton:
					icon: "arrow-right"
					text_color: 0,0,0,1
					on_press: root.set_month(root.month+1)
			DayLabels:
			Dates:
			BoxLayout:
				size_hint: 1, .15
				Status: